[package]
name = "dodge_the_creeps"
version = "0.1.0"
authors = ["The godot-rust developers"]
publish = false
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.1"
rand = "0.7.3"
